package hospital.security;

public enum Permission {

    // Dashboard
    VIEW_DASHBOARD,
    // Patient Management
    REGISTER_PATIENT,
    VIEW_PATIENTS,
    FIND_PATIENT,
    UPDATE_PATIENT,
    DELETE_PATIENT,
    VIEW_PATIENT_PROFILE,
    VIEW_MEDICAL_HISTORY,
    VIEW_PATIENT_APPOINTMENTS,
    VIEW_PATIENT_ADMISSIONS,
    VIEW_PATIENT_PRESCRIPTIONS,
    VIEW_PATIENT_BILLING,
    // Staff Management
    REGISTER_STAFF,
    VIEW_STAFF,
    FIND_STAFF,
    UPDATE_STAFF,
    DELETE_STAFF,
    VIEW_STAFF_BY_DEPARTMENT,
    MANAGE_STAFF_ACCOUNTS,
    // Appointments
    CREATE_APPOINTMENT,
    VIEW_APPOINTMENTS,
    FIND_APPOINTMENT,
    UPDATE_APPOINTMENT,
    DELETE_APPOINTMENT,
    VIEW_PATIENT_APPOINTMENTS_MANAGEMENT,
    VIEW_DOCTOR_APPOINTMENTS,
    // Admission & Bed Management
    CREATE_ADMISSION,
    VIEW_ADMISSIONS,
    FIND_ADMISSION,
    UPDATE_ADMISSION,
    DISCHARGE_PATIENT,
    MANAGE_BEDS,
    // Clinical Management
    VIEW_CLINICAL_RECORDS,
    CREATE_MEDICAL_RECORD,
    UPDATE_MEDICAL_RECORD,
    CREATE_DIAGNOSIS,
    VIEW_DIAGNOSIS,
    CREATE_TREATMENT,
    VIEW_TREATMENT,
    PRESCRIBE_MEDICATION,
    // Laboratory
    VIEW_LABORATORY,
    ORDER_LAB_TEST,
    PERFORM_LAB_TEST,
    VIEW_LAB_RESULTS,
    UPDATE_LAB_RESULTS,
    // Pharmacy
    VIEW_PHARMACY,
    VIEW_MEDICATIONS,
    MANAGE_MEDICATIONS,
    DISPENSE_MEDICATION,
    VIEW_PRESCRIPTIONS,
    MANAGE_PRESCRIPTIONS,
    // Billing & Payment
    VIEW_BILLING,
    CREATE_INVOICE,
    UPDATE_INVOICE,
    DELETE_INVOICE,
    VIEW_INVOICE,
    PROCESS_PAYMENT,
    VIEW_PAYMENT_HISTORY,
    // Hospital Administration
    ACCESS_HOSPITAL_ADMINISTRATION,
    MANAGE_DEPARTMENTS,
    MANAGE_HOSPITAL_SETTINGS,
    VIEW_HOSPITAL_REPORTS,
    VIEW_AUDIT_LOGS,
    // User Account Management
    VIEW_OWN_PROFILE,
    UPDATE_OWN_PROFILE,
    CHANGE_OWN_PASSWORD,
    MANAGE_USERS,
    CREATE_USER,
    UPDATE_USER,
    DEACTIVATE_USER,
    // System
    LOGOUT
}